{
 "title": "Kafka Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Kafka Messages In Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_messagesin_total[5m])",
     "legendFormat": "messages/sec"
    }
   ]
  },
  {
   "title": "Kafka Topic Offset (user_profile_stream)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kafka_topic_partition_current_offset{topic=\"user_profile_stream\"}",
     "legendFormat": "Partition {{partition}}"
    }
   ]
  },
  {
   "title": "Kafka Bytes In/Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_bytesin_total[5m])",
     "legendFormat": "Bytes In"
    },
    {
     "expr": "rate(kafka_server_brokertopicmetrics_bytesout_total[5m])",
     "legendFormat": "Bytes Out"
    }
   ]
  }
 ]
}