global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "kafka-exporter"
    static_configs:
      - targets: ["kafka-exporter:9308"]
      
  - job_name: "airflow"
    metrics_path: /metrics
    static_configs:
      - targets: ["airflow-webserver:8080"]
        labels:
          service: "airflow-webserver"
      - targets: ["airflow-scheduler:8974"]
        labels:
          service: "airflow-scheduler"

  - job_name: "spark"
    static_configs:
      - targets: ["spark-master:7077"]
        labels:
          service: "spark-master"
      - targets: ["spark-worker:7077"]
        labels:
          service: "spark-worker"

  - job_name: "cassandra"
    static_configs:
      - targets: ["cassandra_db:9042"]
        labels:
          service: "cassandra"
